package com.example.projectfinaltth.data.model.request;

import com.google.gson.annotations.SerializedName;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor

public class AddToCartRequest {

    @SerializedName("courseId")
    private String courseId;

    @SerializedName("cartId")
    private String cartId;

    // Constructor with courseId only
    public AddToCartRequest(String courseId) {
        this.courseId = courseId;
    }

    // Constructor with courseId and cartId
    public AddToCartRequest(String courseId, String cartId) {
        this.courseId = courseId;
        this.cartId = cartId;
    }

    // Getters and setters are generated by Lombok (@Data)
}
